/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupPinRouteImport } from './routes/setup-pin'
import { Route as SendOnceOffRouteImport } from './routes/send-once-off'
import { Route as SendRouteImport } from './routes/send'
import { Route as ResetPinRouteImport } from './routes/reset-pin'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayBeneficiaryIdRouteImport } from './routes/pay-beneficiary.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPinRoute = SetupPinRouteImport.update({
  id: '/setup-pin',
  path: '/setup-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SendOnceOffRoute = SendOnceOffRouteImport.update({
  id: '/send-once-off',
  path: '/send-once-off',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPinRoute = ResetPinRouteImport.update({
  id: '/reset-pin',
  path: '/reset-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBeneficiaryIdRoute = PayBeneficiaryIdRouteImport.update({
  id: '/pay-beneficiary/$id',
  path: '/pay-beneficiary/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/reset-pin': typeof ResetPinRoute
  '/send': typeof SendRoute
  '/send-once-off': typeof SendOnceOffRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/pay-beneficiary/$id': typeof PayBeneficiaryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/reset-pin': typeof ResetPinRoute
  '/send': typeof SendRoute
  '/send-once-off': typeof SendOnceOffRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/pay-beneficiary/$id': typeof PayBeneficiaryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/reset-pin': typeof ResetPinRoute
  '/send': typeof SendRoute
  '/send-once-off': typeof SendOnceOffRoute
  '/setup-pin': typeof SetupPinRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/pay-beneficiary/$id': typeof PayBeneficiaryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficiaries'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/redeem'
    | '/reset-pin'
    | '/send'
    | '/send-once-off'
    | '/setup-pin'
    | '/signup'
    | '/verify'
    | '/pay-beneficiary/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficiaries'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/redeem'
    | '/reset-pin'
    | '/send'
    | '/send-once-off'
    | '/setup-pin'
    | '/signup'
    | '/verify'
    | '/pay-beneficiary/$id'
  id:
    | '__root__'
    | '/'
    | '/beneficiaries'
    | '/history'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/redeem'
    | '/reset-pin'
    | '/send'
    | '/send-once-off'
    | '/setup-pin'
    | '/signup'
    | '/verify'
    | '/pay-beneficiary/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RedeemRoute: typeof RedeemRoute
  ResetPinRoute: typeof ResetPinRoute
  SendRoute: typeof SendRoute
  SendOnceOffRoute: typeof SendOnceOffRoute
  SetupPinRoute: typeof SetupPinRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  PayBeneficiaryIdRoute: typeof PayBeneficiaryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-pin': {
      id: '/setup-pin'
      path: '/setup-pin'
      fullPath: '/setup-pin'
      preLoaderRoute: typeof SetupPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-once-off': {
      id: '/send-once-off'
      path: '/send-once-off'
      fullPath: '/send-once-off'
      preLoaderRoute: typeof SendOnceOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-pin': {
      id: '/reset-pin'
      path: '/reset-pin'
      fullPath: '/reset-pin'
      preLoaderRoute: typeof ResetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-beneficiary/$id': {
      id: '/pay-beneficiary/$id'
      path: '/pay-beneficiary/$id'
      fullPath: '/pay-beneficiary/$id'
      preLoaderRoute: typeof PayBeneficiaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RedeemRoute: RedeemRoute,
  ResetPinRoute: ResetPinRoute,
  SendRoute: SendRoute,
  SendOnceOffRoute: SendOnceOffRoute,
  SetupPinRoute: SetupPinRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  PayBeneficiaryIdRoute: PayBeneficiaryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
